# Password Cracking {-}

There is two big families or strategies for cracking passwords:  
1. Brute force attacks
1. Dictionary attacks

Brute forcing is the strategy that concist of trying every possible combination of characters until finding the right secret. Given **enough time**, a brute force
attack is **always successful**.

> So the big question is why attacker not only use this technic? 

The answer is simple. Attackers need **enough time** to do that. Imagine a password with a length of 10 characters containing lowercase chars, uppercase chars,
numbers and special chars, Attackers have to generate `90^10` passwords and that will take ages (years in this case).

> [ ! ] NOTE: That means that attackers will use Brute force strategie only when they have no more possiblities. 

Dictionary attack strategy is a type of bruteforcing but taking as input a dictionary of common credentials or password. This technic is the most used because it's 
not taking so much time as brute force. Of course this strategy is not so efficient as the brute force one because if the credential we want to crack is not in
this dictionary, we will not be able to find the secret. It exist a lot of typical dictionary on the web like [OWASP Seclists Project](https://www.owasp.org/index.php/OWASP_SecLists_Project),
[danielmiessler/Seclist](https://github.com/danielmiessler/SecLists)

## Password Cracking with JohnTheRipper {-}

John The Ripper also known as **john** is a command line tool that can perform brute force attacks and dictionary attacks.

### Use John for brute force {-}

**John** have an option call incremental that permors brute force attacks.

```bash
john -incremental -users:<users list> <file to crack>
```

### Use John for dictionary attack {-}

**John** have the wordlist option to perform dictionary attacks.

```bash
john -wordlist=/usr/share/wordlists/rockyou.txt <file to crack>
```

### Cracking ssh keys protected by password {-}

John The Ripper have a spectial tool called **ssh2john** that help by a dictionary attack to find the 
password used when a user have generated a SSH Key with a passphrase.

usage:

```bash
ssh2john -> /usr/share/john/ssh2john.py id_rsa > hash
cat hash
john --wordlist=/usr/share/wordlists/rockyou.txt hash
```

### Cracking ftp protected by password {-}

John have a special tool for cracking ftp protected by password: **zip2john**

usage:

```bash
zip2john -> /usr/share/john/zip2john backup.zip > hash
cat hash
john --wordlist=/usr/share/wordlists/rockyou.txt hash
```


## Use websites for cracking password {-}

- [crack station](https://crackstation.net)
- [hash killer](https://hashkiller.io)
- [hashes](https://hashes.com)

## Authentication Cracking {-}

When pentesters need to access a network service, they can try to obtain valid credentials by using bruteforce or dictionary attacks.
The problem here is that perfoming thos kinds of attacks through the network can be time consuming for managing every runs (delays, processing and network latency).

> The only feasible solution here is to perform dictionary attacks and hope that a user have a weak or default credentials.


### Authentication Cracking with Hydra {-}

**Hydra** is a fast parallelized, network authentication cracker that supports different protocols like ssh, ftp, smb, rdp, telnet and much more...

usage:
```bash
hydra -L users_dict.txt -P password_dict.txt 127.0.0.1 ssh
```

## Break known hash algorithms with CyberChef {-}

**CyberChef** is a webapp that allows attacker to crack password hash algorithms. You can find the web app on [cyberchef github pages](https://gchq.github.io/CyberChef/).
